# Generated by Django 4.2 on 2023-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.category', verbose_name=' العنصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' المنتج'),
        ),
    ]
