# Generated by Django 4.2.4 on 2023-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0003_alter_available_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم المسلسل'),
        ),
    ]
