# Generated by Django 4.2.4 on 2023-09-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0004_alter_product_options_remove_product_discription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellprocess',
            options={'verbose_name': '  عملية بيع', 'verbose_name_plural': ' عمليات بيع'},
        ),
        migrations.AddField(
            model_name='sellprocess',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ البيع'),
        ),
    ]
